import type { Metadata } from "next";
import {  Tilt_Neon } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";

const font = Tilt_Neon({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider session={session}>
      <Component {...pageProps} />
    </SessionProvider>
      <body className={ `  ${font.className}  `}>{children}</body>
     
    </html>
  );
}

import { SessionProvider } from "next-auth/react"

