import type { Metadata } from "next";
import {  Tilt_Neon } from "next/font/google";
import "./globals.css";

const font = Tilt_Neon({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ ` overflow-hidden ${font.className}`}>{children}</body>
    </html>
  );
}
